### ISSUE TITLE
Create a logo for bumbershoot

### ISSUE THREAD

**Issue by sflandergan** [deviceinsight/bumbershoot#9]
It would be great if someone could create a logo for bumbershoot

**Comment by tanwanimohit** [comment]
Which type of logo do you want? A logo containing the name ? or a logo with with some clip art ?

**Comment by captainIoT** [comment]
I would like to tackle this!

**Comment by trybick** [comment]
Here's one idea

![logo](https://user-images.githubusercontent.com/39889198/66579114-4b016280-eb4a-11e9-8206-1cc4e4efef72.png)

**Comment by sflandergan** [comment]
Thanks @trybick. I'd love to have a logo, that involves umbrellas. 
Bumbershoot is a tool for better managing umbrella helm-charts, therefore I used this old word for umbrella :)

**Comment by trybick** [comment]
Here is one with umbrellas. I can change the colors if you want, or get a different design if this one isn't the best fit.

![logo](https://user-images.githubusercontent.com/39889198/66588218-f8c83d80-eb59-11e9-869a-cc29fa77d47b.png)

**Comment by sflandergan** [comment]
@trybick I like it. Do you want to create a pull request? :)

**Comment by trybick** [comment]
@sflandergan Great! Would putting it in a something like `src/images/logo.png` work?

**Comment by sflandergan** [comment]
oh I would just put it under `images/logo.png` or just under `logo.png`. Shouldn't be bundled with the code but used as logo in the readme :)
